import type { ChecklistTemplate } from "@/lib/seo-checklist";

export const CRO_AUDIT_CHECKLIST: ChecklistTemplate[] = [
  {
    key: "entry-experience",
    title: "First Impression and Entry Experience",
    priority: "critical",
    description: "Popup timing, overlay friction, and immediate clarity in first seconds.",
  },
  {
    key: "hero-clarity",
    title: "Hero and Above-the-Fold Clarity",
    priority: "critical",
    description: "Visible headline, clear value proposition, and primary CTA above the fold.",
  },
  {
    key: "value-proposition",
    title: "Value Proposition and Messaging",
    priority: "high",
    description: "Benefit-led copy, USP clarity, and objection handling in messaging.",
  },
  {
    key: "cta-audit",
    title: "Call To Action Quality",
    priority: "critical",
    description: "CTA visibility, strength, consistency, and placement along user flow.",
  },
  {
    key: "sticky-cta",
    title: "Sticky CTA Presence",
    priority: "high",
    description: "Checks whether a persistent CTA remains accessible while users scroll.",
  },
  {
    key: "cta-accessibility",
    title: "CTA Accessibility and Tap Usability",
    priority: "high",
    description: "Checks button-like styling, tap-size readiness, and mobile usability signals.",
  },
  {
    key: "pricing-transparency",
    title: "Pricing Transparency",
    priority: "critical",
    description: "Price visibility, click distance to pricing, and anchor framing.",
  },
  {
    key: "click-distance",
    title: "Click Distance to Purchase",
    priority: "high",
    description: "Measures how quickly users can reach pricing/checkout from landing.",
  },
  {
    key: "social-proof",
    title: "Social Proof and Trust Signals",
    priority: "critical",
    description: "Testimonials, ratings, guarantees, trust badges, and credibility cues.",
  },
  {
    key: "trust-cta-proximity",
    title: "Trust Signals Near CTA",
    priority: "high",
    description: "Verifies trust cues are placed close to conversion actions.",
  },
  {
    key: "nav-architecture",
    title: "Navigation and Information Architecture",
    priority: "high",
    description: "Conversion path clarity and friction from navigation structure.",
  },
  {
    key: "funnel-friction",
    title: "Funnel Friction Points",
    priority: "critical",
    description: "Checkout path obstacles, form friction, and conversion blockers.",
  },
  {
    key: "form-friction-detail",
    title: "Form Friction Detail",
    priority: "high",
    description: "Required-field load, optional-field ratio, and inline validation clarity.",
  },
  {
    key: "offer-communication",
    title: "Product and Offer Communication",
    priority: "high",
    description: "Feature context, objection handling, and scannable decision support.",
  },
  {
    key: "checkout-confidence",
    title: "Checkout Confidence Signals",
    priority: "high",
    description: "Shipping, returns, warranty, and payment-confidence messaging near purchase.",
  },
  {
    key: "intent-mismatch",
    title: "Intent Mismatch Detector",
    priority: "high",
    description: "Compares headline, title, and CTA intent consistency.",
  },
  {
    key: "technical-health",
    title: "Technical and Metadata Health",
    priority: "high",
    description: "Meta setup, social tags, schema presence, and client-side stability.",
  },
  {
    key: "mobile-experience",
    title: "Mobile Conversion Experience",
    priority: "critical",
    description: "Tap usability, readability, and mobile friction risks.",
  },
  {
    key: "support-objections",
    title: "Support and Objection Handling",
    priority: "medium",
    description: "Visible support channels and answers to buyer objections.",
  },
  {
    key: "urgency-incentives",
    title: "Urgency and Incentive Triggers",
    priority: "medium",
    description: "Scarcity, urgency, free shipping, and risk-reversal cues.",
  },
  {
    key: "analytics-tracking",
    title: "Analytics and Tracking Foundation",
    priority: "high",
    description: "Core analytics, tag manager, and conversion event instrumentation.",
  },
];
