import type { ChecklistTemplate } from "@/lib/seo-checklist";

export const CRO_AUDIT_CHECKLIST: ChecklistTemplate[] = [
  {
    key: "entry-experience",
    title: "First Impression and Entry Experience",
    priority: "critical",
    description: "Popup timing, overlay friction, and immediate clarity in first seconds.",
  },
  {
    key: "hero-clarity",
    title: "Hero and Above-the-Fold Clarity",
    priority: "critical",
    description: "Visible headline, clear value proposition, and primary CTA above the fold.",
  },
  {
    key: "hero-dual-cta",
    title: "Hero CTA Strategy Coverage",
    priority: "high",
    description: "Checks for complementary primary and secondary CTAs in the hero.",
  },
  {
    key: "cta-microcopy-reassurance",
    title: "CTA Microcopy Reassurance",
    priority: "high",
    description: "Checks for no-risk reassurance text near hero CTA (trial, no card, cancel anytime).",
  },
  {
    key: "hero-ai-prompt",
    title: "AI Discovery Prompt Presence",
    priority: "medium",
    description: "Checks if uncertainty-reducing AI assistant prompt appears early above the fold.",
  },
  {
    key: "value-proposition",
    title: "Value Proposition and Messaging",
    priority: "high",
    description: "Benefit-led copy, USP clarity, and objection handling in messaging.",
  },
  {
    key: "problem-framing",
    title: "Problem Framing Strength",
    priority: "high",
    description: "Checks if the page names customer pain clearly before diving into features.",
  },
  {
    key: "quantified-outcomes",
    title: "Quantified Outcomes Evidence",
    priority: "high",
    description: "Checks for concrete performance metrics (percentages, multipliers, timelines).",
  },
  {
    key: "before-after-comparison",
    title: "Before/After Comparison Clarity",
    priority: "medium",
    description: "Checks for explicit pain-vs-outcome comparison framing on-page.",
  },
  {
    key: "live-product-proof",
    title: "Live Product Proof Signals",
    priority: "medium",
    description: "Checks for embedded product evidence (real examples, trend cards, view counts, live outputs).",
  },
  {
    key: "cta-audit",
    title: "Call To Action Quality",
    priority: "critical",
    description: "CTA visibility, strength, consistency, and placement along user flow.",
  },
  {
    key: "pricing-model-clarity",
    title: "Pricing Model Clarity",
    priority: "high",
    description: "Flags abstract credit/token models when concrete outcomes/usage are unclear.",
  },
  {
    key: "pricing-plan-positioning",
    title: "Pricing Plan Positioning",
    priority: "medium",
    description: "Checks whether plan names/headings are audience- or outcome-oriented instead of generic.",
  },
  {
    key: "pricing-comparison-clarity",
    title: "Pricing Comparison Clarity",
    priority: "high",
    description: "Checks whether multi-tier pricing is easy to compare (table/matrix style signals).",
  },
  {
    key: "click-distance",
    title: "Click Distance to Purchase",
    priority: "high",
    description: "Measures how quickly users can reach pricing/checkout from landing.",
  },
  {
    key: "social-proof",
    title: "Social Proof and Trust Signals",
    priority: "critical",
    description: "Testimonials, ratings, customer counts, and credibility cues.",
  },
  {
    key: "early-social-proof-badges",
    title: "Early Social Proof Badge Placement",
    priority: "high",
    description: "Checks if 3rd-party badges/awards are visible near hero decision points.",
  },
  {
    key: "testimonial-outcome-quality",
    title: "Testimonial Outcome Quality",
    priority: "high",
    description: "Checks whether testimonials include specific outcomes, names, and roles.",
  },
  {
    key: "testimonial-third-party-verification",
    title: "Testimonial Third-Party Verification",
    priority: "high",
    description: "Checks for external review badges, ratings, or links supporting testimonial credibility.",
  },
  {
    key: "nav-architecture",
    title: "Navigation and Information Architecture",
    priority: "high",
    description: "Conversion path clarity and friction from navigation structure.",
  },
  {
    key: "language-consistency",
    title: "Language Consistency",
    priority: "critical",
    description: "Detects mixed-language content that can break trust and comprehension.",
  },
  {
    key: "funnel-friction",
    title: "Funnel Friction Points",
    priority: "critical",
    description: "Checkout path obstacles, form friction, and conversion blockers.",
  },
  {
    key: "offer-communication",
    title: "Product and Offer Communication",
    priority: "high",
    description: "Feature context, objection handling, and scannable decision support.",
  },
  {
    key: "integration-ecosystem-proof",
    title: "Integration Ecosystem Proof",
    priority: "high",
    description: "Checks if integration compatibility is clearly surfaced with recognizable signals.",
  },
  {
    key: "feature-cta-clarity",
    title: "Feature CTA Clarity",
    priority: "high",
    description: "Flags generic feature CTAs like repeated 'Read more' without action intent.",
  },
  {
    key: "technical-health",
    title: "Technical and Metadata Health",
    priority: "high",
    description: "Meta setup, social tags, schema presence, and client-side stability.",
  },
  {
    key: "mobile-experience",
    title: "Mobile Conversion Experience",
    priority: "critical",
    description: "Tap usability, readability, and mobile friction risks.",
  },
  {
    key: "support-objections",
    title: "Support and Objection Handling",
    priority: "medium",
    description: "Visible support channels plus FAQ-style objection handling content.",
  },
  {
    key: "faq-depth",
    title: "FAQ Depth and Coverage",
    priority: "high",
    description: "Checks FAQ volume for core purchase objections (billing, cancellation, fit, safety).",
  },
  {
    key: "urgency-incentives",
    title: "Urgency and Incentive Triggers",
    priority: "medium",
    description: "Scarcity, urgency, free shipping, and risk-reversal cues.",
  },
  {
    key: "analytics-tracking",
    title: "Analytics and Tracking Foundation",
    priority: "high",
    description: "Core analytics, tag manager, and conversion event instrumentation.",
  },
  {
    key: "final-cta-reinforcement",
    title: "Final CTA Reinforcement",
    priority: "high",
    description: "Checks if end-of-page CTA repeats core actions with clear value recap.",
  },
  {
    key: "footer-cta-clarity",
    title: "Footer CTA Clarity",
    priority: "medium",
    description: "Checks for contextual microcopy and low-friction framing in footer CTAs.",
  },
  {
    key: "security-compliance-badge",
    title: "Security/Compliance Badge Presence",
    priority: "medium",
    description: "Checks for trust/compliance badges (e.g., SOC/ISO) in late-stage decision zones.",
  },
  {
    key: "founder-credibility-story",
    title: "Founder/Story Credibility",
    priority: "medium",
    description: "Checks whether founder/team story includes concrete credibility signals, not only generic copy.",
  },
  {
    key: "affiliate-program-leverage",
    title: "Affiliate Program Leverage",
    priority: "low",
    description: "Checks whether affiliate/community signals are surfaced beyond the footer.",
  },
];
