import type { ChecklistTemplate } from "@/lib/seo-checklist";

export const CRO_AUDIT_CHECKLIST: ChecklistTemplate[] = [
  {
    key: "entry-experience",
    title: "First Impression and Entry Experience",
    priority: "critical",
    description: "Popup timing, overlay friction, and immediate clarity in first seconds.",
  },
  {
    key: "hero-clarity",
    title: "Hero and Above-the-Fold Clarity",
    priority: "critical",
    description: "Visible headline, clear value proposition, and primary CTA above the fold.",
  },
  {
    key: "hero-dual-cta",
    title: "Hero CTA Strategy Coverage",
    priority: "high",
    description: "Checks for complementary primary and secondary CTAs in the hero.",
  },
  {
    key: "cta-microcopy-reassurance",
    title: "CTA Microcopy Reassurance",
    priority: "high",
    description: "Checks for no-risk reassurance text near hero CTA (trial, no card, cancel anytime).",
  },
  {
    key: "hero-ai-prompt",
    title: "AI Discovery Prompt Presence",
    priority: "medium",
    description: "Checks if uncertainty-reducing AI assistant prompt appears early above the fold.",
  },
  {
    key: "value-proposition",
    title: "Value Proposition and Messaging",
    priority: "high",
    description: "Benefit-led copy, USP clarity, and objection handling in messaging.",
  },
  {
    key: "quantified-outcomes",
    title: "Quantified Outcomes Evidence",
    priority: "high",
    description: "Checks for concrete performance metrics (percentages, multipliers, timelines).",
  },
  {
    key: "cta-audit",
    title: "Call To Action Quality",
    priority: "critical",
    description: "CTA visibility, strength, consistency, and placement along user flow.",
  },
  {
    key: "pricing-comparison-clarity",
    title: "Pricing Comparison Clarity",
    priority: "high",
    description: "Checks whether multi-tier pricing is easy to compare (table/matrix style signals).",
  },
  {
    key: "click-distance",
    title: "Click Distance to Purchase",
    priority: "high",
    description: "Measures how quickly users can reach pricing/checkout from landing.",
  },
  {
    key: "social-proof",
    title: "Social Proof and Trust Signals",
    priority: "critical",
    description: "Testimonials, ratings, customer counts, and credibility cues.",
  },
  {
    key: "nav-architecture",
    title: "Navigation and Information Architecture",
    priority: "high",
    description: "Conversion path clarity and friction from navigation structure.",
  },
  {
    key: "language-consistency",
    title: "Language Consistency",
    priority: "critical",
    description: "Detects mixed-language content that can break trust and comprehension.",
  },
  {
    key: "funnel-friction",
    title: "Funnel Friction Points",
    priority: "critical",
    description: "Checkout path obstacles, form friction, and conversion blockers.",
  },
  {
    key: "feature-cta-clarity",
    title: "Feature CTA Clarity",
    priority: "high",
    description: "Flags generic feature CTAs like repeated 'Read more' without action intent.",
  },
  {
    key: "technical-health",
    title: "Technical and Metadata Health",
    priority: "high",
    description: "Meta setup, social tags, schema presence, and client-side stability.",
  },
  {
    key: "support-objections",
    title: "Support and Objection Handling",
    priority: "medium",
    description: "Visible support channels plus FAQ-style objection handling content.",
  },
  {
    key: "faq-depth",
    title: "FAQ Depth and Coverage",
    priority: "high",
    description: "Checks FAQ volume for core purchase objections (billing, cancellation, fit, safety).",
  },
  {
    key: "analytics-tracking",
    title: "Analytics and Tracking Foundation",
    priority: "high",
    description: "Core analytics, tag manager, and conversion event instrumentation.",
  },
  {
    key: "final-cta-reinforcement",
    title: "Final CTA Reinforcement",
    priority: "high",
    description: "Checks if end-of-page CTA repeats core actions with clear value recap.",
  },
  {
    key: "footer-cta-clarity",
    title: "Footer CTA Clarity",
    priority: "medium",
    description: "Checks for contextual microcopy and low-friction framing in footer CTAs.",
  },
];
